global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rules and alerts are read from the specified file(s)
rule_files:
  - rules.yml


alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ '172.16.4.201:9093' ]


scrape_configs:


  - job_name: node
    static_configs:
    - targets:
       - 172.16.4.201:9100
       - 172.16.4.202:9100



  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://172.16.4.202:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.4.201:9121


  - job_name: postgres-exporter
    static_configs:
      - targets: ["172.16.4.202:9187"]



  - job_name: 'alertmanager'
    static_configs:
    - targets: ['172.16.4.201:9093']




  - job_name: cadvisor
    static_configs:
    - targets: ['172.16.4.201:8080']



  - job_name: 'apache'
    static_configs:
      - targets: ['172.16.4.202:9117']
